import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { chromium, type BrowserContextOptions } from "playwright";
import { axloDashboardJourney, assertAxloDashboardScope } from "./journeys/axlo-dashboard.js";

const redact = (value: string) => value.replace(/\b\+?\d[\d ()-]{7,}\d\b/g, "[REDACTED_PHONE]").replace(/(?:bearer|token|password)\s+\S+/gi, "[REDACTED]");
export async function reviewAxloDashboard(storageState?: unknown, artifacts = "artifacts"): Promise<string> {
  const findings: Array<Record<string, unknown>> = []; const browser = await chromium.launch({ headless: true });
  try { const context = await browser.newContext(storageState ? { storageState: storageState as BrowserContextOptions["storageState"] } : {});
    for (const route of axloDashboardJourney.allowedRoutes) { assertAxloDashboardScope(route); const page = await context.newPage(); const consoleErrors: string[] = [], failedRequests: string[] = [];
      page.on("console", m => { if (m.type() === "error") consoleErrors.push(redact(m.text())); }); page.on("requestfailed", r => failedRequests.push(redact(`${r.method()} ${r.url()} ${r.failure()?.errorText ?? "failed"}`)));
      try { const response = await page.goto(new URL(route, axloDashboardJourney.target).href, { waitUntil: "domcontentloaded", timeout: 30_000 }); findings.push({ route, status: response?.status(), title: redact(await page.title()), headings: (await page.locator("h1,h2").allTextContents()).map(redact), consoleErrors, failedRequests }); } catch (error) { findings.push({ route, error: redact(error instanceof Error ? error.message : String(error)), consoleErrors, failedRequests }); } finally { await page.close(); }
    } await context.close();
  } finally { await browser.close(); }
  mkdirSync(artifacts, { recursive: true }); const base = `axlo-dashboard-review-${new Date().toISOString().replace(/[:.]/g,"-")}`; const path = join(artifacts, `${base}.json`); const report = { journey: axloDashboardJourney.id, generatedAt: new Date().toISOString(), findings, noMutationAttempted: true }; writeFileSync(path, JSON.stringify(report, null, 2)); const safe = (v: string) => v.replace(/[&<>]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;"})[c]!); const failed = findings.filter(x => Number(x.status ?? 0) >= 400 || x.error); const rows = findings.map(x => `<tr><td>${safe(String(x.route))}</td><td class="${Number(x.status ?? 0) < 400 ? "pass" : "fail"}">${safe(String(x.status ?? "Failed"))}</td><td>${safe(String(x.title ?? "—"))}</td><td>${Array.isArray(x.consoleErrors) ? x.consoleErrors.length : 0}</td></tr>`).join(""); const issues = failed.length ? failed.map(x => `<li><strong>${safe(String(x.route))}</strong> returned ${safe(String(x.status ?? "an error"))}. ${safe(Array.isArray(x.consoleErrors) ? x.consoleErrors.join(" ") : "")}</li>`).join("") : "<li>No route failures observed.</li>"; writeFileSync(join(artifacts, `${base}.html`), `<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Axlo dashboard findings</title><style>body{font:16px/1.5 system-ui;max-width:1000px;margin:40px auto;color:#172554}header,.card{border:1px solid #dbe3ef;border-radius:10px;padding:24px;margin:16px 0}.pass{color:#166534;font-weight:700}.fail{color:#b91c1c;font-weight:700}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #dbe3ef;text-align:left}code{background:#f1f5f9;padding:2px 5px}</style><header><p>Nova governed journey</p><h1>Axlo dashboard findings</h1><p>QA · Restaurant Owner · ${safe(report.generatedAt)}</p></header><section class="card"><h2>Summary</h2><p><strong>${findings.length - failed.length}</strong> routes available · <strong>${failed.length}</strong> anomalies · No mutation attempted: <strong>Yes</strong></p></section><section class="card"><h2>Key findings</h2><ul>${issues}</ul></section><section class="card"><h2>Route verification</h2><table><tr><th>Route</th><th>Status</th><th>Page title</th><th>Console errors</th></tr>${rows}</table></section><section class="card"><h2>Scope and evidence</h2><p>Only approved read-only routes were requested. Credentials, tokens, and phone-like values are redacted. Machine-readable evidence: <code>${safe(path)}</code></p></section>`); return path.replace(/\.json$/, ".html");
}
